[workspace]
resolver = "2"

members = [
    "cli",
    "core",
    "daemon",
    "proto",
    "sdk",
]

[workspace.package]
version = "0.1.0"
authors = ["Arane Aimer <araneaimer@gmail.com>"]
license = "AGPL-3.0-only"
edition = "2021"
repository = "https://github.com/hypersend-app/hypersend"